services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment: 
      MONGO_INTTDB_ROOT_USERNAME:  ${MONGODB_USERNAME}
      MONGO_INTTDB_ROOT_PASSWORD:  ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - dbdata:/var/libs/mongodb/data

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_PASSWORD}
    depends_on:
      - mongo

volumes:
  dbdata:   
